// Deployment config for the OpenClaw chat front-end.
// Generated by netlify.toml from BRIDGE_BASE_URL at build time.
// Empty baseUrl means same-origin bridge; Netlify deploys should set BRIDGE_BASE_URL.
window.OPENCLAW_CONFIG = {
  baseUrl: "",
};
